### ISSUE TITLE
I would really appreciate it if it was possible for you to send me the payload

### ISSUE THREAD

**Issue by natem6886** [Ekultek/BlueKeep#31]
I would really appreciate it if it was possible for you to send me the payload
email: mcreeeee1000@gmail.com

**Comment by slightlybent1** [comment]
It dont get much better than that.
https://www.youtube.com/watch?v=mrTQxUa8g2M

**Comment by dart1337** [comment]
> It dont get much better than that.
> https://www.youtube.com/watch?v=mrTQxUa8g2M

it dont work :) seems like problem not in payload

**Comment by Ekultek** [comment]
lol what the actual fuck is that video? Look guys, you don’t just insert payload here and off you go that’s not how this works. There’s no magical payload that will make all your problems go away. You have to actually work for it. So far three people have been able to turn this into the rce because they looked for it and worked on it. The comments are bullshit, I just put that in there to watch everyone lose their minds (worked really well). So having said that, enjoy the day and have a fun.
